### ISSUE TITLE
Getting error message when running

### ISSUE THREAD

**Issue by MostHated** [kidsil/hugo-data-to-pages#2]
Hey there,  
I was quite excited to try this out as it is exactly what I was hoping to locate functionality wise, though, when I went to test it out with the demo content, I received the following error:

```sh
/mnt/e/GitHub/hugo-data-to-pages(master*) » node hugo.js
Building data-generated files...
Created file: example/content/paul-mccartney/index.md
Created file: example/content/john-lennon/index.md
Created file: example/content/george-harrison/index.md
Created file: example/content/ringo-starr/index.md
Running Hugo (build)...
Error: Error building site: "/mnt/e/GitHub/hugo-data-to-pages/example/content/_index.md:1:1": plain HTML documents not supported
(node:364) UnhandledPromiseRejectionWarning: Error: Command failed: (cd example/ && /mnt/e/_programming/go/bin/hugo)
Error: Error building site: "/mnt/e/GitHub/hugo-data-to-pages/example/content/_index.md:1:1": plain HTML documents not supported

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at main (/mnt/e/GitHub/hugo-data-to-pages/hugo.js:115:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

It looks like it produces a file of _index.md, but that file just contains HTML. If I manually change that file to become index.html then trying to run the hugo server against the demo directory after the fact, the demo site works. The actual flow of events when running hugo.js must need some adjustments so as not to produce an md file containing html?

**Comment by kidsil** [comment]
Hey,
This is an error I haven't seen before. Generating an MD file containing HTML shouldn't be a problem (as my script is merely a wrapper, it's hugo that renders the files in the end).

I'm not sure if this problem is related to the hugo.js wrapper, or simply a hugo problem..
Try running `node hugo.js generate` - is it able to build the website?

**Comment by MostHated** [comment]
Hey there, no worries, it was a decent while ago. I ended up spending some time getting more familiar with JS and just rewriting the whole thing to better suit my needs and finished up my site already.

**Comment by kidsil** [comment]
Interesting. Would be great to see the fork you made, if it's generally
useful to others that is..

**Comment by MostHated** [comment]
I am not sure it would be, but I didn't make a fork because I was simply using the package at first. I had the files downloaded to my pc and was just tweaking small things here and then but then added in functionality to take an image folder based on the name of the file included in the data and create thumbnails from any images in the folder using a Golang package I came across.  

The more I was working on my site the more I found it would be easier to try and just maintain the files individually as frontmatter files because the one yaml was becoming a pain to maintain, so I ended up creating a new script using some parts of yours as a framework (the config and argument passing sections) to basically do the opposite. I took the end result that yours generated and used the grey-matter library to convert them back to frontmatter files.

This was what I had added in for image resizing: (using this package https://github.com/noelyahan/mergi)

```js
			if (!pages[j].fields.type) pages[j].fields.type = config.type; // After this line of your original code

			// Automatic image resize to create thumbnails
			if (resize) {
				let imageFiles;
				try {
					imageFiles = fs.readdirSync(`${config.root}/static/images/${pages[j].path}/${pages[j].fields.name}/`);
				} catch (e) {
					return console.log('e', e);
				}
				const { execSync } = require('child_process');
				for (let i in imageFiles) {
					// Console.log('Image name: ' + imageFiles[i]);
					const imgBase = imageFiles[i].split('.');
					if (imgBase[0].includes('_small')) continue;
					console.log('Image base: ' + imgBase[0]);
					const tmpOldImage = `${config.root}/static/images/${pages[j].path}/${pages[j].fields.name}/${imgBase[0]}.png`;
					const tmpNewImage = `${config.root}/static/images/${pages[j].path}/${pages[j].fields.name}/${imgBase[0]}_small.png`;
					const tmpImage = tmpOldImage.toLowerCase();
					const newImage = tmpNewImage.toLowerCase();
					const mergiString = `.\\mergi.exe -i  ${tmpImage} -r "300 178" -o ${newImage} `;

					try {
						await execSync(mergiString);
					} catch (e) {
						return console.log('e', e);
					}
					console.log('Rezied image: ' + newImage);
				}
			}
```
